version: '3.9'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: wordpress-db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: yoyo5555

  wordpress:
    image: wordpress:latest
    container_name: wordpress-test
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: yoyo5555
      WORDPRESS_DB_NAME: wordpress
  
    depends_on:
      - db

volumes:
  db_data:
  wordpress_data:
